# Use
version: 2
jobs:
  build:    
    docker:
      - image: circleci/python:3.7

    working_directory: ~/myfirstdevops
  
    steps:
    #obtain from github
      - checkout
        #2 create virtual env and deps
      - run:
          name: install dependencies          
          command: |
            python3 -m venv venv
            - venv/bin/activate
            pip install -r requirements.txt
      # run linter and tests
      - run:
          name: run tests
          command: |
            - venv/bin/activate
            flake8 --exclude=env* --statistics
            # pytest -v --cov=calculator
            pytest --junixml=test-results/junit.xml

      - store_test_results:
          path: test_results

      - store_artifacts:
          path: test-results

